// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prayer.Data;

#nullable disable

namespace Prayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prayer.Models.PrayerRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Esha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fajar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Maghrib")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PrayerDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Zuhr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PrayerRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
